name: Secure DevSecOps Pipeline

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

# STRICT LEAST PRIVILEGE
permissions:
  contents: read
  security-events: write
  id-token: write
  packages: write

jobs:
  security_audit:
    name: CodeQL SAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: actions

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4


