name: CodeQL

on:
  push:
    branches:
      - master

jobs:
  codeql:
    name: Analyze
    runs-on: ubuntu-latest
    
    steps:
      - name: passsword
        run: echo "my password is RAHAM123"


  
